--The script to initialize the schema was sourced from the Spring Batch Core dependency: org.springframework.batch.core.
\c challenge;

CREATE SCHEMA IF NOT EXISTS document_schema;
SET search_path TO document_schema;

CREATE TABLE document_schema.document_users(
    id        INT     NOT NULL,
    username  VARCHAR(25) NULL,
    password  VARCHAR(150) NULL,
    full_name VARCHAR(100) NULL,
    CONSTRAINT pk_document_users PRIMARY KEY (id)
);

CREATE TABLE document_schema.document_metadata(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_name VARCHAR(50)           NOT NULL,
    created_at    timestamp             NOT NULL,
    file_size     INT                   NOT NULL,
    owner_id      INT                   NOT NULL,
    CONSTRAINT pk_document_metadata PRIMARY KEY (id)
);

CREATE TABLE document_schema.document_tags(
    document_id BIGINT  NOT NULL,
    tag         VARCHAR(20) NOT NULL
);

ALTER TABLE document_schema.document_metadata
    ADD CONSTRAINT FK_DOCUMENT_METADATA_ON_OWNER FOREIGN KEY (owner_id) REFERENCES document_schema.document_users (id);

ALTER TABLE document_schema.document_tags
    ADD CONSTRAINT fk_document_tags_on_document_metadata FOREIGN KEY (document_id) REFERENCES document_schema.document_metadata (id);

-- Indexes for performance
CREATE INDEX idx_document_metadata ON document_schema.document_metadata (document_name, owner_id);
CREATE INDEX idx_document_tags ON document_schema.document_tags (tag);

-- Grant privileges to the DOC_MANAGER user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA document_schema TO doc_manager;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA document_schema TO doc_manager;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA document_schema TO doc_manager;
-- Set search_path for the user
ALTER ROLE doc_manager SET search_path TO document_schema, public;
