#Spring Boot Configuration
spring.application.name=Document Management Service Application
#JPA Configuration Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
#Servlet Multipart Configuration Settings
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
#Embedded Web Server Settings
server.tomcat.max-connections=150
server.tomcat.threads.max=15
server.tomcat.max-keep-alive-requests=25
server.tomcat.accept-count=25
#Loggers
logging.level.com.clara.ops.challenge.document_management_service_challenge=info
