#Spring Boot Configuration
spring.application.name=Document Management Service Application
#JPA Configuration Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
#Servlet Multipart Configuration Settings
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
#Loggers
logging.level.com.clara.ops.challenge.document_management_service_challenge=info
