services:
  postgresql:
    container_name: postgresql_container
    image: bitnamilegacy/postgresql:15.4.0
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME=DOC_MANAGER
      - POSTGRESQL_PASSWORD=DOC_MANAGER_2026
      - POSTGRESQL_DATABASE=challenge
      - POSTGRESQL_POSTGRES_PASSWORD=admin_postgres_2026 # Password of user "postgres"
  minio:
    # Downgraded the version of minio to a Community release image that supports
    #  access key features in the web console
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # MinIO Web Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio_2026
    command: server --console-address ":9001" /data
    networks:
      - batch_network
    volumes:
      - challenge_minio_data:/data
  dms:
    container_name: dms_app
    image: clara/document-management-service-challenge:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/challenge
      SPRING_DATASOURCE_USERNAME: DOC_MANAGER
      SPRING_DATASOURCE_PASSWORD: DOC_MANAGER_2026
      APP_DOCUMENT_STORAGE_BUCKET_NAME: dms
      APP_DOCUMENT_STORAGE_ENDPOINT_URL: http://minio:9000/
      APP_DOCUMENT_STORAGE_ACCESS_KEY: LIwNgkpZ1wjPrLG0Pz61
      APP_DOCUMENT_STORAGE_SECRET_KEY: gpFb2RldNcWeAkHW17M3QGuaigIWEWTlY4o1QNro
    command:
      - -Dspring.aot.enabled=true
    networks:
      - batch_network
    deploy:
      resources:
        limits:
          memory: 50M
    depends_on:
      - postgresql
      - minio

volumes:
  challenge_postgresql_data:
    driver: local
  challenge_minio_data:
    driver: local

networks:
  batch_network:
    driver: bridge
